import type { Metadata } from "next";
import { fonts } from "./fonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AntdLayout from "./components/antd-layout/antd-layout";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <AntdRegistry>
          <AntdLayout>{children}</AntdLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
